// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestInstagramTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testInstagram() {
    driver.Navigate().GoToUrl("https://www.instagram.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1280, 680);
    driver.FindElement(By.Name("username")).Click();
    driver.FindElement(By.Name("username")).SendKeys("stcdcdcdcdy1");
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.Name("password")).SendKeys("Scdcddcd4");
    driver.FindElement(By.CssSelector(".\\_acan > .\\_ab8w")).Click();
    driver.FindElement(By.CssSelector(".\\_acao")).Click();
    driver.FindElement(By.CssSelector(".\\_ab8w > .\\_aarf .xh8yej3")).Click();
    driver.FindElement(By.CssSelector(".\\_abm0 > .\\_ab6-")).Click();
    driver.FindElement(By.CssSelector(".\\_a9--:nth-child(11)")).Click();
  }
}
