// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestfacebookTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testfacebook() {
    driver.Navigate().GoToUrl("https://www.facebook.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1280, 680);
    driver.FindElement(By.Id("pass")).Click();
    driver.FindElement(By.Id("pass")).SendKeys(Keys.Enter);
    driver.FindElement(By.Id("pass")).SendKeys("Stoyanov@1234");
    {
      var element = driver.FindElement(By.CssSelector(".x6s0dn4:nth-child(2) > .x4k7w5x .x1i10hfl:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".x4k7w5x > .x1n2onr6 image"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".x4k7w5x > .x1n2onr6 .xbh8q5q"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector(".x4k7w5x > .x1n2onr6 > .x1i10hfl g")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".x9f619 > .x1n2onr6 > .x9f619 > .x9f619 > .x78zum5 > .x9f619 > .x1i10hfl > .x9f619"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector("div:nth-child(5) > .x1i10hfl .x193iq5w")).Click();
    driver.FindElement(By.Id("email")).SendKeys("nikitig1987@abv.bg");
    driver.FindElement(By.Id("pass")).SendKeys("Stoyanov@1234");
  }
}
