// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace SeleniumCsharp

{
    [TestFixture]
public class TestJira4Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testJira4() {
    driver.Navigate().GoToUrl("http://jira.softacad.bg/secure/Dashboard.jspa");
    driver.Manage().Window.Size = new System.Drawing.Size(1296, 696);
    driver.FindElement(By.Id("login-form-username")).SendKeys("ncdcdcdnov");
    driver.FindElement(By.Id("login-form-password")).Click();
    driver.FindElement(By.Id("login-form-password")).SendKeys("Bdcdcddc6");
    driver.FindElement(By.Id("login")).Click();

  }
    }
}